=== anyweez/smelt.io/schema/challenge.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Sor Challenge Definition",
    "description": "An individual challenge in the Sor challenge database.",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The challenge title for display purposes."
        },
        "description": {
            "type": "object",
            "properties": {
                "short": { "type": "string" },
                "full": { "type": "string" }
            },
            "required": ["short", "full"]
        },
        "added_by": {
            "type": "string",
            "description": "An alphanumeric username for the user who submitted the challenge."
        },
        "added_on": {
            "type": "string",
            "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}",
            "description": "YYYY-MM-DD when the challenge was added to the repository."
        },
        "status": {
            "type": "object",
            "description": "Flags related to where and whether the challenge should appear.",
            "properties": {
                "available": {
                    "type": "boolean"
                }
            }
        },
        "spec": {
            "type": "object",
            "properties": {
                "func": { "type": "string" },
                "parameters": { "type": "array" },
                "returns": { "type": "string" },
                "examples": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "inputs": { "type": "array" },
                            "output": { "type": "boolean" }
                        }
                    }
                }
            },
            "required": ["func", "parameters", "returns"]
        },
        "tests": { 
            "type": "string" ,
            "description": "Path to the file containing tests for this problem."
        }
    },
    "required": ["name", "description", "added_by", "added_on", "spec", "tests"],
    "additionalProperties": false
}

=== anyweez/smelt.io/challenges/chemistry.json
{
    "name": "Splurthian Chemistry",
    "description": {
        "short": "Find valid chemical symbols in an imaginary periodic table.",
        "full": "The inhabitants of the planet Splurth are building their own periodic table of the elements. Just like Earth's periodic table has a chemical symbol for each element (H for Hydrogen, Li for Lithium, etc.), so does Splurth's. However, their chemical symbols must follow certain rules:\n\n 1. All chemical symbols should be exactly two letters long.\n\n 2. Both letters in the symbol must appear in the element name.\n\n 3. The letters in the symbol must appear in the same order in the symbol and element name."
    },

    "added_by": "/u/Cosmologicon",
    "added_on": "2016-08-25",
    "status": {
        "available": true
    },

    "spec": {
        "func": "chemistry",
        "parameters": ["string", "string"],
        "returns": "boolean",
        "examples": [{
            "inputs": ["'Hydrogen'", "'Yg'"],
            "output": true
        },{
            "inputs": [["'Iron'", "'Or'"]],
            "output": false
        },{
            "inputs": [["'Gold'", "'G'"]],
            "output": false
        }]
    },
    
    "tests": "chemistry.js"
}

=== anyweez/smelt.io/challenges/scatterpack.json
{
    "name": "Scatterpack",
    "description": {
        "short": "Determine if arrays contain the same elements.",
        "full": "Determine if two shuffled arrays of numbers contain the same elements. You cannot use `Array.prototype.sort()`."
    },

    "added_by": "anyweez",
    "added_on": "2016-08-20",
    "status": {
        "available": true
    },

    "spec": {
        "func": "scatterpack",
        "parameters": ["array", "array"],
        "returns": "boolean",
        "examples": [{
            "inputs": ["[1, 2, 3]", "[3, 2, 1]"],
            "output": true
        },{
            "inputs": ["[1, 1, 2]", "[1, 2, 1]"],
            "output": true
        },{
            "inputs": ["[4, 9, 1, 8]", "[4, 9]"],
            "output": false
        }]
    },
    
    "tests": "scatterpack.js"
}

=== anyweez/smelt.io/challenges/slide.json
{
    "name": "Sliding along",
    "description": {
        "short": "Compute the sliding average of a set of numbers.",
        "full": "Write a function that returns an object with two function properties: `add(number)`, which adds a new value, and `get()`, which returns the average of the (up to) four most recently added values."
    },

    "added_by": "anyweez",
    "added_on": "2016-08-21",
    "status": {
        "available": true
    },

    "spec": {
        "func": "slide",
        "parameters": [],
        "returns": "object"
    },
    
    "tests": "slide.js"
}

=== anyweez/smelt.io/challenges/blackjack.json
{
    "name": "Blackjacked",
    "description": {
        "short": "Determine whether a blackjack hand busts or not",
        "full": "[Blackjack](https://en.wikipedia.org/wiki/Blackjack) is a card game where the goal is to get as close to 21 points without going over.  Face cards count as ten points, numbered cards are worth the value shown on their face, and aces can be worth either one or eleven (player's choice). Players 'bust' when they exceed 21 points, and lose the hand. Write a function that returns true when the provided deck busts (totals more than 21) and false when it doesn't."
    },

    "added_by": "anyweez",
    "added_on": "2016-08-18",
    "status": {
        "available": true
    },

    "spec": {
        "func": "blackjack",
        "parameters": ["array"],
        "returns": "boolean",
        "examples": [{
            "inputs": [[5, 7, 2, "'Q'"]],
            "output": true
        },{
            "inputs": [["'Q'", "'J'"]],
            "output": false
        },{
            "inputs": [["'A'", "'Q'", 2]],
            "output": false
        }]
    },
    
    "tests": "blackjack.js"
}

=== anyweez/smelt.io/challenges/nemo.json
{
    "name": "Nemo lost at sea",
    "description": {
        "short": "Simulate Nemo's chances of survival.",
        "full": "Nemo was caught in a terrible storm and flung into the sea with only a life raft, fishing pole, and ten fish to his name. Write a function that accepts two parameters: the probability that Nemo will catch a fish on a given day, and the number of days he needs to survive before being rescued, and returns the probability of surviving the provided number of days, rounded to two decimal places. Assume that Nemo needs to eat one fish per day to survive."
    },

    "added_by": "anyweez",
    "added_on": "2016-08-21",
    "status": {
        "available": true
    },

    "spec": {
        "func": "nemo",
        "parameters": ["number", "number"],
        "returns": "number"
    },
    
    "tests": "nemo.js"
}
